name: Auto Deploy
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
 
jobs:
  compile:
    runs-on: ubuntu-latest
    name: Running Java 
    steps:
    - uses: actions/checkout@master
    - name: Set up JDK 17
      uses: actions/setup-java@master
      with:
        java-version: '17'
        distribution: 'adopt'
        cache: maven
    - name: Build with Maven
      run: mvn clean package --file pom.xml
    - name: Publish to server
      uses: garygrossgarten/github-action-scp@release
      with:
          local: target/liangyu-oj-0.0.1-SNAPSHOT.jar
          remote: /home/ubuntu/java/liangyu-oj-0.0.1-SNAPSHOT.jar
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
    - name: Deploy
      uses: appleboy/ssh-action@master
      with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            cd /home/ubuntu/java
            sh run.sh
